### ISSUE TITLE
Seeing the following error when trying to get to any of the az iot ops commands

### ISSUE THREAD

**Issue by colinrippeyfinarne** [Azure/azure-iot-ops-cli-extension#106]
My az --version is:

azure-cli                         2.54.0

core                              2.54.0
telemetry                          1.1.0

Extensions:
arcappliance                      0.2.31
azure-iot-ops                    0.1.0b1
connectedk8s                      1.3.20
connectedvmware                   0.1.12
customlocation                     0.1.3
k8s-extension                      1.4.1

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\ColinRippey\.azure\cliextensions'

Python (Windows) 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:21:31) [MSC v.1936 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.

When I run az iot --help I see:

D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\cryptography/hazmat/backends/openssl/backend.py:27: UserWarning: You are using cryptography on a 32-bit Python on a 64-bit Windows Operating System. Cryptography will be significantly faster if you switch to using a 64-bit Python.
Unable to load extension 'azure-iot-ops: No module named 'kubernetes.client.exceptions''. Use --debug for more information.

Group
    az iot : Manage Internet of Things (IoT) assets.

Subgroups:
    central : Manage IoT Central resources.
    dps     : Manage Azure IoT Hub Device Provisioning Service.
    hub     : Manage Azure IoT hubs.

To search AI knowledge base for examples, use: az find "az iot"

I'm guessing the line Unable to load extension is an issue that needs resolving, happy to provide more details and/or try steps.

**Comment by digimaun** [comment]
@colinrippeyfinarne thanks for submitting this issue.

Can you please try updating (or removing) the `arcappliance` extension you have installed? There is a dependency conflict issue which should be resolved with one of those two mentioned options.

**Comment by colinrippeyfinarne** [comment]
> Hi @colinrippeyfinarne, I cannot repro the issue with same version of the extension you installed. However, have you try uninstall and reinstall the kubernetes using `pip install kubernetes` to see if that fix the issue? And could you also provide the --debug output if it's not fixed? thanks for the patience.

I'll try this today and also the suggestion from @digimaun and let you know the results.

**Comment by digimaun** [comment]
Closing the issue. If you are still running into problems after trying the suggested, let us know and we can re-open.
