### ISSUE TITLE
[bug] usage of CLI behind corporate proxy

### ISSUE THREAD

**Issue by derbl4ck** [Azure/azure-iot-ops-cli-extension#111]
**Describe the bug**
If youre sitting behind a corporate proxy, the connection to _management.azure.com_ is (depending on company config) only possible if using `HTTP_PROXY` environment variable. Since this http-call is done at a later step, there will be a new EntraID App created for each (failed) CLI-execution try.

**To Reproduce**

1. Create a new arc-enabled AKS Edge Essentials system
2. Use a PC sitting behind a corporate proxy
3. Execute CLI-Command to install Azure IoT Operations on this existing system

**Expected behavior**
We should have a preflight http-call to check if all needed endpoints are availible. If not available, there should be a hint, that if using a corporate proxy, the `HTTP_PROXY` environment variable should be configured.

**Screenshots**
```bash
az iot ops init --subscription xxxxx -g rg-xxxxx --cluster xxxxx-aksee001 --kv-id /subscriptions/xxxxx/resourceGroups/rg-xxxxx/providers/Microsoft.KeyVault/vaults/kv-xxxxx --no-deploy
Command group 'iot ops' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

Azure IoT Operations init
Workflow Id: 036db351c9a94b4f8bb69513da6ae807

-> KeyVault CSI Driver
     ✔ Created app '50dcc418-187a-4fd3-a45c-5f8f8c8a54a1'
     - Ensure KeyVault 'kv-xxxxx' access policy
     - Ensure secret name 'azure-iot-operations' for service account
     - Deploy driver to cluster
     - Configure driver
   TLS
     - Generate test CA using 'secp256r1'
     - Configure cluster for tls
   Deploy IoT Operations [skipped]

⠏ DONE! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   Elapsed: 0:01:35

(<urllib3.connection.HTTPSConnection object at 0x076E24F0>, 'Connection to management.azure.com timed out. (connect timeout=300)')
```

**Environment (please complete the following information):**

- OS: Windows 10 Enterprise
- Shell: powershell
- Az CLI version: 2.54.0
- IoT extension version: 0.1.0b2

**Additional context**
This should make the usage of Azure IoT Operations more battle-safe for enterprise customers. Depending on CLI-config and different engineers working on the topic, this is a situation that should be covered.

**Comment by digimaun** [comment]
@derbl4ck Thank you for making the suggestion. This is supported in `v0.3.0b1` +

Use `az extension add --upgrade --name azure-iot-ops` to install the latest.
