### ISSUE TITLE
[bug] az iot ops init with arguments ----ca-file and --ca-key-file fails due to secret name not matched by ARM template

### ISSUE THREAD

**Issue by katriendg** [Azure/azure-iot-ops-cli-extension#123]
**Describe the bug**
When executing the `az iot ops init` command and passing arguments for pre-created CA file and CA key such as below, there is a mismatch in secret and configmap names generated by the CLI vs what the ARM template is using which is also used by the CLI command.

Sample command used: 

```
az iot ops init --cluster $CLUSTER_NAME -g $RESOURCE_GROUP --kv-id $MY_KV_RID \
    --ca-file ./temp/primary_intermediate_ca.crt \
    --ca-key-file ./temp/primary_intermediate_ca.key
```

**To Reproduce**

1. Run through the typical AIO quickstart, enabling the Arc extension on the cluster.
2. Prepare a CA root and key file.
3. Run the `az iot ops init` command adding the parameters to point to the CA and CA Key files
4. See error starts appearing as the Arc Extension 'azure-iot-operation' gets installed. If looking into the pods, the `aio-orc-api-xxx` pod fails to startup because of a mount that is failing via Configmap `aio-ca-trust-bundle-test-only` that cannot be found. This is because the above arguments generate a configmap named `aio-ca-trust-bundle` instead of `aio-ca-trust-bundle-test-only`. Same issue for the trust secret name.

**Expected behavior**
I should be able to supply my own cert root and key, and additionally the name of the secret and configmaps should be parameterizable. Some customers might want to skip TLS setup and point to an existing Trust configmap, and an existing Secret for the key and ca file. Especially when we look at production environments with cert renewal worklows.

The actual issue is in the CLI, there is a mismatch in the name of the secret and configmapgs generated when executing with and without the --ca-file and key parameters, see this section of code:
https://github.com/Azure/azure-iot-ops-cli-extension/blob/a0fbcdc71edec0bf44603b3b21ebd1529f6da3d0/azext_edge/edge/providers/orchestration/base.py#L150 
Note the configmap and secret don't have `-test-only` appended.
While when the ARM template runs it has hard-coded 'test-only' appended: https://github.com/Azure/azure-iot-ops-cli-extension/blob/a0fbcdc71edec0bf44603b3b21ebd1529f6da3d0/azext_edge/edge/providers/orchestration/template.py#L111

**Screenshots**

**Environment (please complete the following information):**

- OS: [e.g. Windows 11, WSL Ubuntu 20.04]
- Shell: wsl bash
- Az CLI version: 2.56.0
- IoT extension version: 0.2.0b2
- Python version (if pip installed): n/a

**Additional context**

**Comment by digimaun** [comment]
@katriendg , I'm not able to repro the issue using the example command you provided. After running, AIO was deployed successfully.

> The actual issue is in the CLI, there is a mismatch in the name of the secret and configmapgs generated when executing with and without the --ca-file and key parameters, see this section of code:

The CLI `init` flow should change the name of the template variables to what is appropriate with respect to a user provided CA vs a generated test CA. That happens here:

https://github.com/Azure/azure-iot-ops-cli-extension/blob/a0fbcdc71edec0bf44603b3b21ebd1529f6da3d0/azext_edge/edge/providers/orchestration/work.py#L447

After my fresh deployment the following relevant secret exists 

![image](https://github.com/Azure/azure-iot-ops-cli-extension/assets/28658112/bfeb39e4-718b-43d1-90ed-3995e7455cb6)

And the following relevant configmap 

![image](https://github.com/Azure/azure-iot-ops-cli-extension/assets/28658112/a5cb7028-fddd-41e6-945b-1d3c4978f320)

And if I look at the deployment template that `init` kicks off, I see variables are changed as expected

![image](https://github.com/Azure/azure-iot-ops-cli-extension/assets/28658112/57007c2d-e3a8-4bcf-a509-43c498a6e961)

**Comment by katriendg** [comment]
Hello @digimaun - thanks a lot for going through a validation and confirming. I have executed it again on a clean cluster setup and can confirm my installation also succeeded. I'm not sure why before I had the issue and could not get past the installation of the `orc-` portion of the installation.

Thanks for highlighting the code section where the variables contents get updated to remove the '-test-only' section. I can confirm I see the same in the deployment template in the Portal.
